spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://localhost:3306/xx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# mybatis-plus 配置内容
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # ID 自增主键
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xx.entity

logging:
  level:
    # 开启 debug 模式 mybatis 输入 sql
    com:
      xx:
        mapper: debug
